### ISSUE TITLE
order of slides

### ISSUE THREAD

**Issue by ilemhadri** [PeterTheOne/slideslive-slides-dl#1]
Currently the slides are downloaded and named with no particular order, which makes reading and following in order difficult.
It would be great if the downloaded slides can be sorted in the order through which they are presented in the original video.

**Comment by PeterTheOne** [comment]
If I download with `python3 slideslive-slides.dl.py https://slideslive.de/38919334/technical-seo-and-modern-javascript-web-apps` I get file names like `0-2725-big-0.jpg`, `0-2726-big-41000.jpg`, `0-2727-big-80000.jpg`, etc. The order seems fine to me, if I sort them in my file explorer by name they appear in that order. What filesnames and order do you get? Please provide an example.

**Comment by ilemhadri** [comment]
I agree that on many examples, the filenames output by the script naturally reflect the order.
However, here is an example where this is not the case:

`python3 slideslive-slides.dl.py https://slideslive.com/38917774/`

The video has several people speaking and presenting slides. There are two issues with the filenames output:
-- The slides from a given presenter are not all in the right order
-- Slides from different people are merged together.

**Comment by PeterTheOne** [comment]
Interesting, please check if https://github.com/PeterTheOne/slideslive-slides-dl/pull/2 works for you. Haven't tried yet, I'll merge it if it works.

**Comment by ilemhadri** [comment]
Much better now! Thanks.
