### ISSUE TITLE
Missing audio

### ISSUE THREAD

**Issue by binaondrej** [PeterTheOne/slideslive-slides-dl#11]
slideslive-slides-dl successfully downloads all slides and their durations, but after merging to mp4 using ffmpeg, the final video dowsn't contain audio. (And it looks like the audio wasn't neither downloaded)

**Comment by binaondrej** [comment]
sorry, my fault. In desctioption is written "only downloads slides"

**Comment by PeterTheOne** [comment]
np, just use youtube-dl.. and add the audio with ffmpeg

**Comment by binaondrej** [comment]
yep, thats the way how I have done it 😅

**Comment by khawar-islam** [comment]
@binaondrej Please let me know how you add the audio?
