### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by ilemhadri** [PeterTheOne/slideslive-slides-dl#9]
Thanks for the very useful script. Could the script be modified somehow to allow downloading of text subtitles when they are available? If not, any suggestions for how to retrieve subtitles for slideslive videos would be apprecaited.

**Comment by PeterTheOne** [comment]
You're welcome! Out of scope for this script.

Do you know about `youtube-dl`? They seem to have some options to download subtitles, see: https://superuser.com/a/927532/176911 But I'm not sure if it that option works for slideslive, if not open an issue on https://github.com/ytdl-org/youtube-dl .
